name: Build docker image

on:
  push:
    branches:
    - transport_layer_status
    paths:
    - 'docker/**'
    - 'lib/python/**'
    - 'util/udev/**'
    - 'requirements.txt'
    - '.github/workflows/build-publish-qmk_basedevel-docker-image.yml'
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install python dependencies
        run: ls -l lib/python
      
      # Update the docker files needed for build the image.
      - name: Update context files
        run: cp -r lib/python/* docker/lib/python/ && cp -r util/udev/* docker/util/udev/ && cp requirements.txt docker/

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: plandevida/qmk_basedevel:latest
          context: ./docker
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
