name: Build firmware

on:
  push:
    branches:
    - master
    - transport_layer_status
  pull_request:
    paths:
    - 'lib/python/**'
    - 'bin/qmk'
    - 'requirements.txt'
    - '.github/workflows/cli.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    container: plandevida/qmk_plandevida

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up keyboard
      run: qmk config user.keyboard=crkbd/rev1/common
    - name: Set up keymap
      run: qmk config user.keymap=plandevida-jorne
    - name: Compile keymap left side
      run: qmk clean && qmk compile crkbd-rev1-common-plandevida-jorne-left.hex
    - name: Archive (Jorne Left)
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: crkbd-rev1-common-plandevida-jorne-left.hex
    - name: Prepare compilation for right side 1/2
      run: sed -i 's@#define MASTER_LEFT@//#define MASTER_LEFT@gm' config.h
    - name: Prepare compilation for right side 2/2
      run: sed -i 's@// #define MASTER_RIGHT@#define MASTER_RIGHT@gm' config.h
    - name: Compile keymap right side
      run: qmk clean && qmk compile crkbd-rev1-common-plandevida-jorne-right.hex
    - name: Archive (Jorne Left)
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: crkbd-rev1-common-plandevida-jorne-right.hex
